### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by coderswk** [toblu96/Ti-Track#6]
I am a beginner of AoA positioning. I want to use this project for target location. Which platform should I run this project on? And how to run it?

**Comment by toblu96** [comment]
@coderswk 

Glad to hear that you are interested in AoA positioning. 
Please note that this project only includes the documentation website and only covers the measurement setup and results. This repository does not include code for AoA hardware. I have used hardware from Texas Instruments, on their website you will find more detailed instructions for setting up such a positioning system.
[Texas Instrument - AoA Setup](http://dev.ti.com/tirex/explore/node?node=AHYhhuDNTaRXzkOlahOlvA__pTTHBmu__LATEST&search=aoa)

Here you can find the used hardware:
[BoostXL-AoA - Antenna array](https://www.ti.com/tool/BOOSTXL-AOA)
[LAUNCHXL-CC26X2R1](https://www.ti.com/tool/LAUNCHXL-CC26X2R1) (since CC2640R2 is no longer supported)

I hope this helps.
